const K={doctors:"ammara_doctors_final",patients:"ammara_patients_final",procedures:"ammara_procedures_final",services:"ammara_services_final",expenses:"ammara_expenses_final",pass:"ammara_password_final",shifts:"ammara_shifts_final"};
let doctors=load(K.doctors,[{id:1,name:"Doctor 1",fee:500,active:true},{id:2,name:"Doctor 2",fee:500,active:true},{id:3,name:"Doctor 3",fee:500,active:true},{id:4,name:"Doctor 4",fee:500,active:true}]);
let patients=load(K.patients,[]),procedures=load(K.procedures,[]),services=load(K.services,[{id:1,name:"BP Check",fee:100},{id:2,name:"Sugar Check",fee:150},{id:3,name:"Injection",fee:200},{id:4,name:"Dressing",fee:300}]),expenses=load(K.expenses,[]);
let shifts=load(K.shifts,{morningStart:"08:00",morningEnd:"20:00",eveningStart:"20:00",eveningEnd:"08:00"});if(localStorage.getItem(K.pass)===null)localStorage.setItem(K.pass,"1234");
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function $(id){return document.getElementById(id)}function today(){return new Date().toISOString().slice(0,10)}function money(n){return"Rs. "+Number(n||0).toLocaleString("en-PK")}function esc(v){return String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}function timeNow(){return new Date().toTimeString().slice(0,5)}
function inRange(t,s,e){if(s===e)return true;return s<e?t>=s&&t<e:t>=s||t<e}function getShift(){return inRange(timeNow(),shifts.morningStart,shifts.morningEnd)?"Morning":"Evening"}function shiftBusinessDate(s){let d=new Date(),t=timeNow();if(s==="Evening"&&shifts.eveningStart>shifts.eveningEnd&&t<shifts.eveningEnd)d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)}function shiftKey(d,s){return d+"|"+s}
function login(){if($("loginPassword").value===localStorage.getItem(K.pass)){$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");init()}else $("loginError").textContent="Wrong password"}function logout(){$("app").classList.add("hidden");$("loginScreen").classList.remove("hidden");$("loginPassword").value=""}
function init(){let d=today();["dashboardDate","recordDate","procDate","expenseDate"].forEach(x=>$(x).value=d);renderAll();setInterval(()=>{renderShift();renderDashboard()},30000)}
function renderAll(){renderShift();renderDoctors();renderDoctorSelect();renderProcedures();renderProcedureSelect();renderExpenses();renderDashboard();renderRecords()}
function showTab(id,btn){document.querySelectorAll(".tab-page").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active")}
function renderShift(){let s=getShift();$("shiftBadge").textContent="Current Shift: "+s.toUpperCase();$("currentShiftText").textContent="Current shift: "+s.toUpperCase()}
function addDoctor(){let n=$("doctorName").value.trim(),f=Number($("doctorFee").value);if(!n||!Number.isFinite(f)||f<0)return alert("Doctor name aur OPD fee enter karein");doctors.push({id:Date.now(),name:n,fee:f,active:true});save(K.doctors,doctors);$("doctorName").value="";$("doctorFee").value="";renderDoctors();renderDoctorSelect()}
function renderDoctors(){$("doctorList").innerHTML=doctors.length?doctors.map(d=>`<div class="doctor-row"><div><b>${esc(d.name)}</b> — ${money(d.fee)} <span class="badge ${d.active?"":"off"}">${d.active?"ON":"OFF"}</span></div><div class="doctor-actions"><button class="secondary" onclick="editDoctor(${d.id})">Edit</button><button onclick="toggleDoctor(${d.id})">${d.active?"Turn OFF":"Turn ON"}</button><button class="danger" onclick="deleteDoctor(${d.id})">Delete</button></div></div>`).join(""):"<p>No doctors.</p>"}
function editDoctor(id){let d=doctors.find(x=>x.id===id);if(!d)return;let n=prompt("Doctor name:",d.name);if(n===null)return;let f=prompt("OPD fee (Rs.):",d.fee);if(f===null)return;if(!n.trim()||isNaN(Number(f)))return alert("Invalid data");d.name=n.trim();d.fee=Number(f);patients.forEach(p=>{if(p.doctorId===id)p.doctor=d.name});save(K.doctors,doctors);save(K.patients,patients);renderAll()}
function toggleDoctor(id){let d=doctors.find(x=>x.id===id);if(d){d.active=!d.active;save(K.doctors,doctors);renderDoctors();renderDoctorSelect()}}function deleteDoctor(id){if(confirm("Delete doctor?")){doctors=doctors.filter(x=>x.id!==id);save(K.doctors,doctors);renderAll()}}
function renderDoctorSelect(){let a=doctors.filter(d=>d.active);$("patientDoctor").innerHTML=a.length?'<option value="">Select doctor</option>'+a.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join(""):'<option value="">No active doctor</option>';updateSelectedFee()}function updateSelectedFee(){let d=doctors.find(x=>String(x.id)===$("patientDoctor").value);$("patientFee").value=d?d.fee:""}
function savePatient(){let n=$("patientName").value.trim(),age=$("patientAge").value.trim(),g=$("patientGender").value,d=doctors.find(x=>String(x.id)===$("patientDoctor").value);if(!n||!age||!g||!d)return alert("Name, Age, Gender aur Doctor fill karein");let s=getShift(),bd=shiftBusinessDate(s),key=shiftKey(bd,s),count=patients.filter(p=>p.shiftKey===key&&p.doctorId===d.id).length+1,token=String(count).padStart(3,"0"),now=new Date(),date=today(),time=now.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),p={id:Date.now(),name:n,age,gender:g,doctorId:d.id,doctor:d.name,fee:d.fee,shift:s,shiftKey:key,date,time,token};patients.push(p);save(K.patients,patients);fillReceipt(p);$("tokenNumber").textContent=token;$("tokenDoctor").textContent=d.name;$("tokenShift").textContent=s;$("tokenFee").textContent=d.fee;$("tokenResult").classList.remove("hidden");["patientName","patientAge","patientGender","patientDoctor","patientFee"].forEach(x=>$(x).value="");renderDashboard();renderRecords()}
function fillReceipt(p){$("printToken").textContent=p.token;$("printPatient").textContent=p.name;$("printAge").textContent=p.age;$("printGender").textContent=p.gender;$("printDoctor").textContent=p.doctor;$("printShift").textContent=p.shift;$("printDate").textContent=p.date;$("printTime").textContent=p.time;$("printFee").textContent=Number(p.fee).toLocaleString("en-PK")}function printToken(){window.print()}
function addProcedure(){let n=$("newProcedureName").value.trim(),f=Number($("newProcedureFee").value);if(!n||!Number.isFinite(f)||f<0)return alert("Service name aur fee enter karein");services.push({id:Date.now(),name:n,fee:f});save(K.services,services);$("newProcedureName").value="";$("newProcedureFee").value="";renderProcedures();renderProcedureSelect()}
function renderProcedures(){$("procedureList").innerHTML=services.map(s=>`<div class="procedure-row"><div><b>${esc(s.name)}</b> — ${money(s.fee)}</div><div class="procedure-actions"><button class="secondary" onclick="editProcedure(${s.id})">Edit</button><button class="danger" onclick="deleteProcedure(${s.id})">Delete</button></div></div>`).join("")}
function editProcedure(id){let s=services.find(x=>x.id===id);if(!s)return;let n=prompt("Service name:",s.name);if(n===null)return;let f=prompt("Fee:",s.fee);if(f===null)return;if(n.trim()&&Number.isFinite(Number(f))){s.name=n.trim();s.fee=Number(f);save(K.services,services);renderProcedures();renderProcedureSelect()}}
function deleteProcedure(id){if(confirm("Delete service?")){services=services.filter(x=>x.id!==id);save(K.services,services);renderProcedures();renderProcedureSelect()}}function renderProcedureSelect(){$("procedureSelect").innerHTML='<option value="">Select procedure</option>'+services.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");updateProcedureFee()}function updateProcedureFee(){let s=services.find(x=>String(x.id)===$("procedureSelect").value);$("procAmount").value=s?s.fee:""}
function saveProcedure(){let n=$("procPatient").value.trim(),s=services.find(x=>String(x.id)===$("procedureSelect").value),a=Number($("procAmount").value),d=$("procDate").value||today();if(!n||!s||!Number.isFinite(a)||a<0)return alert("Patient, procedure aur amount fill karein");procedures.push({id:Date.now(),patient:n,procedure:s.name,amount:a,date:d,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});save(K.procedures,procedures);$("procPatient").value="";$("procedureSelect").value="";$("procAmount").value="";renderDashboard();renderRecords();alert("Procedure sale saved")}
function saveExpense(){let n=$("expenseName").value.trim(),a=Number($("expenseAmount").value),d=$("expenseDate").value||today();if(!n||!Number.isFinite(a)||a<0)return alert("Expense name aur amount fill karein");expenses.push({id:Date.now(),name:n,amount:a,date:d,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});save(K.expenses,expenses);$("expenseName").value="";$("expenseAmount").value="";renderExpenses();renderDashboard();renderRecords()}
function renderExpenses(){$("expensesBody").innerHTML=expenses.length?expenses.slice().reverse().map(e=>`<tr><td>${e.date}</td><td>${esc(e.name)}</td><td>${money(e.amount)}</td><td><button class="danger" onclick="deleteExpense(${e.id})">Delete</button></td></tr>`).join(""):'<tr><td colspan="4">No expenses.</td></tr>'}function deleteExpense(id){if(confirm("Delete expense?")){expenses=expenses.filter(x=>x.id!==id);save(K.expenses,expenses);renderExpenses();renderDashboard()}}
function renderDashboard(){let d=$("dashboardDate").value||today(),op=patients.filter(p=>p.date===d),pr=procedures.filter(p=>p.date===d),ex=expenses.filter(e=>e.date===d),os=op.reduce((a,p)=>a+Number(p.fee),0),ps=pr.reduce((a,p)=>a+Number(p.amount),0),es=ex.reduce((a,p)=>a+Number(p.amount),0);$("dashOpdPatients").textContent=op.length;$("dashProcedures").textContent=pr.length;$("dashOpdSale").textContent=money(os);$("dashProcedureSale").textContent=money(ps);$("dashTotalSale").textContent=money(os+ps);$("dashExpenses").textContent=money(es);$("dashNet").textContent=money(os+ps-es);renderShift()}
function renderRecords(){let d=$("recordDate").value||today(),q=($("searchInput").value||"").toLowerCase(),a=patients.filter(p=>p.date===d&&[p.name,p.doctor,p.token,p.shift].join(" ").toLowerCase().includes(q)).map(p=>({type:"OPD",token:p.token,name:p.name,who:p.doctor,shift:p.shift,amount:p.fee,date:p.date,time:p.time,id:p.id,kind:"patient"})),b=procedures.filter(p=>p.date===d&&[p.patient,p.procedure].join(" ").toLowerCase().includes(q)).map(p=>({type:"SERVICE",token:"—",name:p.patient,who:p.procedure,shift:"—",amount:p.amount,date:p.date,time:p.time,id:p.id,kind:"procedure"})),rows=[...a,...b].sort((x,y)=>String(y.time).localeCompare(String(x.time)));$("recordsBody").innerHTML=rows.length?rows.map(r=>`<tr><td>${r.type}</td><td><b>${esc(r.token)}</b></td><td>${esc(r.name)}</td><td>${esc(r.who)}</td><td>${esc(r.shift)}</td><td>${money(r.amount)}</td><td>${r.date}</td><td>${esc(r.time)}</td><td><button class="danger" onclick="${r.kind==="patient"?"deletePatient":"deleteProcedure"}(${r.id})">Delete</button></td></tr>`).join(""):'<tr><td colspan="9">No records found.</td></tr>'}
function deletePatient(id){if(confirm("Delete OPD record?")){patients=patients.filter(x=>x.id!==id);save(K.patients,patients);renderAll()}}function deleteProcedure(id){if(confirm("Delete procedure record?")){procedures=procedures.filter(x=>x.id!==id);save(K.procedures,procedures);renderAll()}}
function exportCSV(){let d=$("recordDate").value||today(),rows=[];patients.filter(p=>p.date===d).forEach(p=>rows.push(["OPD",p.token,p.name,p.doctor,p.shift,p.fee,p.date,p.time]));procedures.filter(p=>p.date===d).forEach(p=>rows.push(["SERVICE","—",p.patient,p.procedure,"—",p.amount,p.date,p.time]));let csv=[["Type","Token","Patient","Doctor/Procedure","Shift","Amount","Date","Time"],...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`ammara-records-${d}.csv`;a.click()}
function openSettings(){$("morningStart").value=shifts.morningStart;$("morningEnd").value=shifts.morningEnd;$("eveningStart").value=shifts.eveningStart;$("eveningEnd").value=shifts.eveningEnd;$("settingsMessage").textContent="";$("settingsModal").classList.remove("hidden")}function closeSettings(){$("settingsModal").classList.add("hidden")}
function saveShiftSettings(){let ms=$("morningStart").value,me=$("morningEnd").value,es=$("eveningStart").value,ee=$("eveningEnd").value;if(!ms||!me||!es||!ee)return alert("All shift times select karein");shifts={morningStart:ms,morningEnd:me,eveningStart:es,eveningEnd:ee};save(K.shifts,shifts);renderAll();$("settingsMessage").textContent="Shift times saved."}
function changePassword(){if($("oldPassword").value!==localStorage.getItem(K.pass))return $("settingsMessage").textContent="Current password wrong";let n=$("newPassword").value.trim();if(n.length<4)return $("settingsMessage").textContent="New password at least 4 characters";localStorage.setItem(K.pass,n);$("oldPassword").value="";$("newPassword").value="";$("settingsMessage").textContent="Password changed successfully"}